FROM docker-local.artifactory.local/bitrix/licenses.roscosmos.ru/php:8-fpm-dev

WORKDIR /app

COPY ./app ./

RUN php composer.phar install --no-dev

RUN chown -R www-data:www-data ./* \
    && chmod -R 775 ./* \
    && find ./* -type f -exec chmod 0664 {} \; \
    && chmod -R 777 /tmp

EXPOSE 9000